version: '3.8'

volumes:
  postgres-data:

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: weather-app
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - '127.0.0.1:5432:5432'
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data

  teddy:
    container_name: weather-app
    build:
      dockerfile: Dockerfile
      context: .
    command: 'node ./dist/main.js'
    restart: unless-stopped
    env_file: .env
    environment:
      - DB_HOST=postgres
    expose:
      - 3000
    ports:
      - '127.0.0.1:3000:3000'